FROM python:3.9-alpine3.13

LABEL MAINTAINER="dextercai"

RUN mkdir /root/sues-os

WORKDIR /root/sues-os
COPY ./ ./

RUN python3 -m pip install --upgrade pip \
    && pip3 install -r requirements-lite.txt \
    && rm -rf ~/.cache

CMD ["/bin/bash"]