FROM python:3.9.8-slim

LABEL MAINTAINER="dextercai"

RUN mkdir /root/sues-os

WORKDIR /root/sues-os
COPY ./ ./

RUN apt-get update -y \
    && apt-get install -y python3-pip \
    && pip3 install -r requirements-lite.txt \
    && rm -rf ~/.cache

CMD ["/bin/bash"]